# Generated by Django 4.0.5 on 2023-06-15 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_car_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': (('visualizar_vehiculos', 'visualizar_vehiculos'),)},
        ),
    ]
